# config.yaml for the Website

# General settings for the website
site:
  name: "Christopher Hirschauer | Blockchain Architect"
  description: "Personal website of Christopher Hirschauer, Blockchain Architect & Python Developer"
  version: "1.0"
  favicon: "/assets/images/favicon.ico"

# Navigation Bar links
nav:
  home: "/index.html"
  about: "/about.html"
  projects: "/projects.html"
  contact: "/contact.html"

# Colors and Theme Settings
theme:
  primary_color: "#7BAFD4"  # Primary accent color (used in buttons, links, etc.)
  background_color: "#1A1A1A"  # Dark background color for the site
  secondary_color: "#0a192f"  # Background color for sections and navigation
  text_color: "#ffffff"  # Main text color (light theme)

# Fonts (from Tailwind config)
fonts:
  heading_font: "Fira Code, monospace"
  body_font: "Fira Code, monospace"

# Social Media Links
social_media:
  twitter: "https://twitter.com/your_username"
  linkedin: "https://linkedin.com/in/your_username"
  github: "https://github.com/your_username"
  email: "mailto:c.hirschauer@outlook.com"

# Banner image for the homepage
banner:
  image_url: "https://i.ibb.co/yFqhRjGg/IMG-0386.png"  # URL to banner image

# Section Visibility (Control visibility of sections dynamically)
sections:
  about_me: true
  specialties: true
  projects: true
  contact: true

# Background Settings
background:
  image_url: "https://i.ibb.co/3mFnchVp/Block-Chain-Data.png"  # Background image URL
  opacity: 0.5  # Opacity of the background image
  fixed: true  # Whether the background image is fixed or scrolls with the page

# Special effects (Canvas/Grid or Animations)
effects:
  canvas_grid: true  # Whether to show the canvas grid animation
  background_particles: false  # Whether to enable particle effects in the background

# Scroll and Fade Effects (For smooth transitions between sections)
scroll:
  smooth_scrolling: true  # Enables smooth scrolling for better UX
  fade_in: true  # Enables fade-in effect for sections when they come into view

# Project Information
projects:
  - name: "Inside the Black Forest"
    description: "Deep dive into MEV strategy and execution."
    link: "https://example.com/project1"
  - name: "Ctrl+C, Ctrl+V, and the Death of Reason"
    description: "A philosophical exploration of automation and reasoning."
    link: "https://example.com/project2"
  - name: "Smart Contracts"
    description: "Engineering the future of business and finance with smart contracts."
    link: "https://example.com/project3"
  - name: "Downloader"
    description: "A user-friendly yt-dlp script for media downloads."
    link: "https://example.com/project4"
  - name: "dexSwapper"
    description: "Multi-token, multi-hop arbitrage execution bot."
    link: "https://example.com/project5"
  - name: "alphaEdge"
    description: "Advanced predictive algorithms for optimized arbitrage."
    link: "https://example.com/project6"
  - name: "autoGAAP"
    description: "Automated tool to scan financial data for GAAP compliance."
    link: "https://example.com/project7"

# Contact Form Settings
contact_form:
  email_recipient: "c.hirschauer@outlook.com"  # Email to receive contact form submissions
  success_message: "Thank you for reaching out! I'll get back to you soon."
  error_message: "Oops! Something went wrong. Please try again later."

# SEO Settings
seo:
  meta_description: "Personal website of Christopher Hirschauer, Blockchain Systems Architect & Python Developer. Explore projects, blogs, and technical insights."
  meta_keywords: "Blockchain, Python Developer, Arbitrage, MEV, Smart Contracts, Crypto, Web3"
  meta_author: "Christopher Hirschauer"
