# config.yaml for the Website

# General settings for the website
site:
  name: "Christopher Hirschauer | Blockchain Architect"
  description: "Personal website of Christopher Hirschauer, Blockchain Architect & Python Developer"
  version: "1.0"
  favicon: "/assets/images/favicon.ico"
  language: "en"
  locale: "en_US"

# Navigation Bar links
nav:
  home: "/index.html"
  about: "/about.html"
  projects: "/projects.html"
  contact: "/contact.html"

# Colors and Theme Settings
theme:
  primary_color: "#7BAFD4"         # Primary accent color (used in buttons, links, etc.)
  background_color: "#1A1A1A"      # Dark background color for the site
  secondary_color: "#0a192f"       # Background color for sections and navigation
  text_color: "#ffffff"            # Main text color (light theme)

# Fonts (from Tailwind config)
fonts:
  heading_font: "Fira Code, monospace"
  body_font: "Fira Code, monospace"

# Social Media Links
social_media:
  twitter: "https://twitter.com/hirschauer_eth"
  linkedin: "https://linkedin.com/in/christopher-hirschauer"
  github: "https://github.com/74Thirsty"
  email: "mailto:c.hirschauer@outlook.com"

# Banner image for the homepage
banner:
  image_url: "https://i.ibb.co/yFqhRjGg/IMG-0386.png"  # URL to banner image

# Section Visibility (Control visibility of sections dynamically)
sections:
  about_me: true
  specialties: true
  projects: true
  contact: true
  blog: false         # Set to true when ready to launch blog

# Background Settings
background:
  image_url: "https://i.ibb.co/3mFnchVp/Block-Chain-Data.png"
  opacity: 0.5
  fixed: true

# Special effects (Canvas/Grid or Animations)
effects:
  canvas_grid: true
  background_particles: false

# Scroll and Fade Effects
scroll:
  smooth_scrolling: true
  fade_in: true

# Dark Mode Configuration
dark_mode:
  enabled: true
  toggle: false  # Set to true if user should be able to switch themes

# Project Information
projects:
  - name: "Inside the Black Forest"
    description: "Deep dive into MEV strategy and execution."
    link: "https://gist.github.com/74Thirsty/a97a5e84d10c5caec0c7281d006ea2cd"

  - name: "Ctrl+C, Ctrl+V, and the Death of Reason"
    description: "A philosophical exploration of automation and reasoning."
    link: "https://example.com/project2"  # Placeholder, no gist provided

  - name: "Smart Contracts"
    description: "Engineering the future of business and finance with smart contracts."
    link: "https://example.com/project3"  # Placeholder, no gist provided

  - name: "Downloader"
    description: "A user-friendly yt-dlp script for media downloads."
    link: "https://gist.github.com/74Thirsty/8c3973574dc01063363a6959dc35a941"

  - name: "dexSwapper"
    description: "Multi-token, multi-hop arbitrage execution bot."
    link: "https://example.com/project5"  # Placeholder, no gist provided

  - name: "alphaEdge"
    description: "Advanced predictive algorithms for optimized arbitrage."
    link: "https://example.com/project6"  # Placeholder, no gist provided

  - name: "autoGAAP"
    description: "Automated tool to scan financial data for GAAP compliance."
    link: "https://gist.github.com/74Thirsty/0501bc09f1464c6e81075b6bd6173550"

  - name: "Auto Docker"
    description: "One-command Dockerizer for Python apps and web services."
    link: "https://gist.github.com/74Thirsty/82e6aa9b225c8f02858788ca9e5b6b9c"

  - name: "BeagleBone Black Setup"
    description: "Initial provisioning and IoT setup for BeagleBone Black SBC."
    link: "https://gist.github.com/74Thirsty/896562e415109d84dc84632ed6bacf3c"

  - name: "VirtualBox Linux Installer"
    description: "Interactive installer script for setting up Linux VMs on VirtualBox."
    link: "https://gist.github.com/74Thirsty/cf9043c370f1ebca309bf37ce41043e7"

# Contact Form Settings
contact_form:
  email_recipient: "c.hirschauer@outlook.com"
  success_message: "Thank you for reaching out! I'll get back to you soon."
  error_message: "Oops! Something went wrong. Please try again later."

# SEO Settings
seo:
  meta_description: "Personal website of Christopher Hirschauer, Blockchain Systems Architect & Python Developer. Explore projects, blogs, and technical insights."
  meta_keywords: "Blockchain, Python Developer, Arbitrage, MEV, Smart Contracts, Crypto, Web3"
  meta_author: "Christopher Hirschauer"
